# Generated by Django 4.1.7 on 2023-03-17 18:58

from django.db import migrations, models
import testapp.school


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('School_id', models.AutoField(primary_key=True, serialize=False)),
                ('studentname', models.CharField(max_length=500)),
                ('studentclass', models.CharField(max_length=500)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(max_length=500)),
                ('pincode', models.CharField(max_length=500)),
                ('password', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('studentclass', models.CharField(max_length=500)),
                ('rollno', models.CharField(max_length=500)),
                ('studentgrade', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=500)),
                ('studentgrade', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('forget_password', models.CharField(blank=True, max_length=500, null=True)),
                ('last_login_time', models.DateTimeField(blank=True, null=True)),
                ('last_logout_time', models.DateTimeField(blank=True, null=True)),
            ],
            managers=[
                ('objects', testapp.school.UserSchool()),
            ],
        ),
    ]
